async function moonscript(moduleArg={}){var moduleRtn;var e=moduleArg,f="./this.program",aa=import.meta.url,q="",r,t;try{q=(new URL(".",aa)).href}catch{}t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};r=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var u=console.log.bind(console),v=console.error.bind(console),x,y=!1,z,A,B,C,D,E,F,G,H=!1;
function I(){var a=B.buffer;C=new Int8Array(a);new Int16Array(a);D=new Uint8Array(a);new Uint16Array(a);E=new Int32Array(a);F=new Uint32Array(a);new Float32Array(a);new Float64Array(a);G=new BigInt64Array(a);new BigUint64Array(a)}function J(a){e.onAbort?.(a);a="Aborted("+a+")";v(a);y=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");A?.(a);throw a;}var K;
async function ba(a){if(!x)try{var b=await r(a);return new Uint8Array(b)}catch{}if(a==K&&x)a=new Uint8Array(x);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var c=await ba(a);return await WebAssembly.instantiate(c,b)}catch(d){v(`failed to asynchronously prepare wasm: ${d}`),J(d)}}
async function da(a){var b=K;if(!x)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){v(`wasm streaming compile failed: ${d}`),v("falling back to ArrayBuffer instantiation")}return ca(b,a)}class ea{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var L=a=>{for(;0<a.length;)a.shift()(e)},M=[],N=[],fa=()=>{var a=e.preRun.shift();N.push(a)},O=!0,P=new TextDecoder,Q=(a,b)=>{for(var c=b+void 0;a[b]&&!(b>=c);)++b;return b},R=a=>a?P.decode(D.subarray(a,Q(D,a))):"",S=a=>0===a%4&&(0!==a%100||0===a%400),ha=[0,31,60,91,121,152,182,213,244,274,305,335],ia=[0,31,59,90,120,151,181,212,243,273,304,334],T=(a,b,c)=>{var d=D;if(!(0<c))return 0;var g=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.codePointAt(k);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=
h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;k++}}d[b]=0;return b-g},U={},ja=()=>{if(!V){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:f||"./this.program"},b;for(b in U)void 0===U[b]?delete a[b]:
a[b]=U[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);V=c}return V},V,ka=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},la=[null,[],[]],ma;e.noExitRuntime&&(O=e.noExitRuntime);e.print&&(u=e.print);e.printErr&&(v=e.printErr);e.wasmBinary&&(x=e.wasmBinary);e.thisProgram&&(f=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();
e.ccall=(a,b,c,d)=>{var g={string:l=>{var m=0;if(null!==l&&void 0!==l&&0!==l){m=ka(l)+1;var p=W(m);T(l,p,m);m=p}return m},array:l=>{var m=W(l.length);C.set(l,m);return m}};a=e["_"+a];var k=[],h=0;if(d)for(var n=0;n<d.length;n++){var w=g[c[n]];w?(0===h&&(h=X()),k[n]=w(d[n])):k[n]=d[n]}c=a(...k);return c=function(l){0!==h&&Y(h);return"string"===b?R(l):"boolean"===b?!!l:l}(c)};
var na,Y,W,X,pa={a:(a,b,c,d)=>J(`Assertion failed: ${R(a)}, at: `+[b?R(b):"unknown filename",c,d?R(d):"unknown function"]),x:()=>{},b:function(){return 0},g:function(){return 0},e:function(){},m:()=>{},o:()=>{},p:()=>{},f:()=>{},j:()=>J(""),n:a=>a?-52:0,k:()=>{throw Infinity;},q:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);E[b>>2]=a.getUTCSeconds();E[b+4>>2]=a.getUTCMinutes();E[b+8>>2]=a.getUTCHours();E[b+12>>2]=a.getUTCDate();E[b+16>>2]=a.getUTCMonth();
E[b+20>>2]=a.getUTCFullYear()-1900;E[b+24>>2]=a.getUTCDay();E[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},r:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();E[b+28>>2]=(S(a.getFullYear())?ha:ia)[a.getMonth()]+a.getDate()-1|0;E[b+36>>2]=-(60*a.getTimezoneOffset());
var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},s:function(a){var b=new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),k=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(k,g);0>c?E[a+32>>2]=Number(g!=k&&h==d):0<c!=(h==d)&&(g=Math.max(k,g),b.setTime(b.getTime()+
6E4*((0<c?h:g)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=(S(b.getFullYear())?ha:ia)[b.getMonth()]+b.getDate()-1|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=b.getDate();E[a+16>>2]=b.getMonth();E[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},t:(a,b,c,d)=>{var g=(new Date).getFullYear(),k=(new Date(g,0,1)).getTimezoneOffset();g=(new Date(g,6,1)).getTimezoneOffset();F[a>>2]=60*Math.max(k,g);E[b>>2]=Number(k!=g);b=h=>{var n=Math.abs(h);return`UTC${0<=
h?"-":"+"}${String(Math.floor(n/60)).padStart(2,"0")}${String(n%60).padStart(2,"0")}`};a=b(k);b=b(g);g<k?(T(a,c,17),T(b,d,17)):(T(a,d,17),T(b,c,17))},i:function(a,b,c){if(!(0<=a&&3>=a))return 28;G[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},h:()=>Date.now(),l:a=>{var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-B.buffer.byteLength+65535)/
65536|0;try{B.grow(d);I();var g=1;break a}catch(k){}g=void 0}if(g)return!0}return!1},v:(a,b)=>{var c=0,d=0,g;for(g of ja()){var k=b+c;F[a+d>>2]=k;c+=T(g,k,Infinity)+1;d+=4}return 0},w:(a,b)=>{var c=ja();F[a>>2]=c.length;a=0;for(var d of c)a+=ka(d)+1;F[b>>2]=a;return 0},z:a=>{O||(e.onExit?.(a),y=!0);throw new ea(a);},c:()=>52,y:()=>52,u:function(){return 70},d:(a,b,c,d)=>{for(var g=0,k=0;k<c;k++){var h=F[b>>2],n=F[b+4>>2];b+=8;for(var w=0;w<n;w++){var l=a,m=D[h+w],p=la[l];0===m||10===m?(l=1===l?u:
v,m=Q(p,0),m=P.decode(p.buffer?p.subarray(0,m):new Uint8Array(p.slice(0,m))),l(m),p.length=0):p.push(m)}g+=n}F[d>>2]=g;return 0},A:oa};function oa(a,b,c){var d=X();try{ma.get(a)(b,c)}catch(g){Y(d);if(g!==g+0)throw g;na(1,0)}}var Z;
Z=await (async function(){function a(c){Z=c.exports;B=Z.B;I();ma=Z.F;c=Z;e._run_moonscript=c.D;e._compile_moonscript=c.E;na=c.G;Y=c.H;W=c.I;X=c.J;return Z}var b={a:pa};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,g)=>{c(a(d,g))})});K??=e.locateFile?e.locateFile?e.locateFile("moonscript.wasm",q):q+"moonscript.wasm":(new URL("moonscript.wasm",import.meta.url)).href;return a((await da(b)).instance)}());
(function(){function a(){e.calledRun=!0;if(!y){H=!0;Z.C();z?.(e);e.onRuntimeInitialized?.();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();M.push(b)}L(M)}}if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)fa();L(N);e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);a()},1)):a()})();H?moduleRtn=e:moduleRtn=new Promise((a,b)=>{z=a;A=b});
;return moduleRtn}export default moonscript;
